---
# [ lvm_storage - tasks/lvm_volume.yml ]

- ansible.builtin.include_vars: "./roles/lvm_volume/defaults/main.yml"
  run_once: true
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]

- ansible.builtin.include_vars: "{{ lvm_storage_vars_file.path }}"
  run_once: true
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]

- ansible.builtin.include_role:
    name: lvm_volume
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]
