---
# [ lvm_storage - tasks  ]

- name: Check mandatory variables
  ansible.builtin.assert:
    that:
      - lvm_storage_vars_file_find_patterns != []
    quiet: true
    msg: "Mandatory variables have to be defined!"
  run_once: false
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]


# Install LVM packages
- name: Install LVM packages
  ansible.builtin.package:
    name: "{{ lvm_packages }}"
    state: present
  notify: daemon-reload
  tags: [ install-lvm_packages ]


# List block devices
- block:
    - name: List block devices
      ansible.builtin.command: lsblk
      register: sys_lsblk
      changed_when: false

    - ansible.builtin.debug:
        msg: "{{ sys_lsblk.stdout_lines }}"

  tags: [ never, list-lvm_sys_block_devices ]


# Get storage vars
- name: Get storage vars
  ansible.builtin.find:
    paths: "{{ lvm_storage_vars_files_path }}"
    file_type: file
    use_regex: true
    patterns: "{{ lvm_storage_vars_file_find_patterns }}"
  register: lvm_storage_vars
  become: false
  delegate_to: localhost
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]

- ansible.builtin.include_tasks:
    file: "roles/{{ role_name }}/tasks/lvm_volume.yml"
  with_items: "{{ lvm_storage_vars.files }}"
  loop_control:
    loop_var: lvm_storage_vars_file
  tags: [ set-lvm_lvol, get-lvm_lvol_preview, remove-lvm_lvol ]
